### ISSUE TITLE
Frontend Styling

### ISSUE THREAD

**Issue by Yakup3** [Yakup3/text-to-speech#1]
I would like the front end to be more pretty, with some decent styling to get better view.

**Comment by BexFox** [comment]
Hi, 
Why don't you use MUI? It's React UI tools.
[https://mui.com/](https://mui.com/)
You can use it just by using like `"import Button from '@mui/material/Button";`
Or It could be a good sample to make it prettier!

I'm the one who got help from you few days ago! Greeting! 👋

**Comment by Yakup3** [comment]
Hi,
Thank you very much. I have not used but I will try it.
It's great if I could help you 🙂
